### ISSUE TITLE
A HandlerFunc without writing a response body causes weird error

### ISSUE THREAD

**Issue by syumai** [syumai/workers#101]
* A HandlerFunc without writing response body causes weird error.
* This issue was originally reported in #100 .

```go
func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		// doing nothing here causes weird error
	})
	workers.Serve(nil) // use http.DefaultServeMux
}
```

```
$ curl localhost:8787
TypeError: Cannot read properties of undefined (reading 'exports')
    at syscall/js.valueNew (file:///home/syumai/go/src/github.com/syumai/workers-playground/syumai-workers-repro-issue-100/build/wasm_exec.js:395:24)
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at [object Object]
    at globalThis.Go._resume (file:///home/syumai/go/src/github.com/syumai/workers-playground/syumai-workers-repro-issue-100/build/wasm_exec.js:553:23)
    at Object.handleRequest (file:///home/syumai/go/src/github.com/syumai/workers-playground/syumai-workers-repro-issue-100/build/wasm_exec.js:564:8)
    at Object.fetch (file:///home/syumai/go/src/github.com/syumai/workers-playground/syumai-workers-repro-issue-100/build/shim.mjs:51:18)
    at async jsonError (file:///home/syumai/.nvm/versions/node/v20.12.2/lib/node_modules/wrangler/templates/middleware/middleware-miniflare3-json-error.ts:22:10)
```

### How to reproduce

Run `How to reproduce` steps in the repository below.

https://github.com/syumai/workers-playground/tree/main/syumai-workers-repro-issue-100

**Comment by ibrunotome** [comment]
I'm receiving the same error with the code below:

```go
package main

import (
	"crypto/tls"
	"net/http"
	"net/http/httputil"
	"net/url"

	"github.com/syumai/workers"
)

func NewProxy(targetHost string, isFramer bool) *httputil.ReverseProxy {
	target, _ := url.Parse(targetHost)
	proxy := httputil.NewSingleHostReverseProxy(target)
	originalDirector := proxy.Director
	proxy.Director = func(req *http.Request) {
		originalDirector(req)
		req.Header.Set("X-Real-IP", req.RemoteAddr)
		req.Header.Set("X-Forwarded-For", req.RemoteAddr)
		req.Header.Set("X-Forwarded-Proto", req.URL.Scheme)

		if isFramer {
			req.Host = target.Host
			req.URL.Path = "/"
		} else {
			req.Host = "example.com"
		}
	}

	if isFramer {
		proxy.Transport = &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
		}
	}

	return proxy
}

func main() {
	landingProxy := NewProxy("https://example1.framer.wiki", true)
	influencerProxy := NewProxy("https://example2.framer.wiki", true)
	appProxy := NewProxy("https://example.com", false)

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" {
			landingProxy.ServeHTTP(w, r)
		} else if r.URL.Path == "/influenciador" {
			influencerProxy.ServeHTTP(w, r)
		} else {
			appProxy.ServeHTTP(w, r)
		}
	})

	workers.Serve(nil)
}
```

**Comment by guregu** [comment]
I have another reproduction, with the latest version and Go. It worked with tinygo + Go 1.23, I believe.
Repo: https://github.com/guregu/worker-bug-1

```go
package main

import (
	"embed"
	"net/http"

	"github.com/syumai/workers"
)

//go:embed assets
var assetsFS embed.FS

func main() {
	http.Handle("/", http.FileServer(http.FS(assetsFS)))
	workers.Serve(nil)
}
```

Accessing a file throws this error.

**Comment by syumai** [comment]
I've release v0.29.0. Now, repro project below is fixed.
https://github.com/syumai/workers-playground/tree/main/syumai-workers-repro-issue-100

I'll check another comments.

**Comment by syumai** [comment]
This comment appears to be related to an issue with FixedTransformStream.
https://github.com/syumai/workers/issues/101#issuecomment-2718681263

**Comment by syumai** [comment]
@guregu The problem you reported (https://github.com/syumai/workers/issues/101#issuecomment-2718681263) has been fixed in [v0.30.1](https://github.com/syumai/workers/releases/tag/v0.30.1).
Thank you for reporting this! 🙏 
see: https://github.com/syumai/guregu-worker-bug-repro

**Comment by guregu** [comment]
@syumai Awesome, thank you! 🎉
