### ISSUE TITLE
Occasional panic in cloudflare/fetch.NewIncomingProperties()

### ISSUE THREAD

**Issue by Skee** [syumai/workers#119]
I'm seeing an occasional panic triggered in NewIncomingProperties due to the `cf` object sometimes not including an `asn` attr.

Here are the relevant bits of a log entry:

```
      "stack": "RuntimeError: unreachable\n    at main.runtime._panic (wasm://wasm/main-0021d66a:wasm-function[27]:0x3833)\n    at main.github.com/syumai/workers/cloudflare/fetch.NewIncomingProperties (wasm://wasm/main-0021d66a:wasm-function[273]:0x6d6e8)\n    at main.main.handleRequest (wasm://wasm/main-0021d66a:wasm-function[130]:0x3388d)\n    at main.github.com/syumai/workers.handleRequest$1$gowrapper (wasm://wasm/main-0021d66a:wasm-function[268]:0x69041)\n    at main.tinygo_rewind (wasm://wasm/main-0021d66a:wasm-function[19]:0x651)\n    at main.resume.command_export (wasm://wasm/main-0021d66a:wasm-function[302]:0x78648)\n    at global.Go._resume (worker.js:470:26)\n    at worker.js:480:12\n    at new Promise (<anonymous>)\n    at syscall/js.valueNew (worker.js:362:44)",
      "name": "Error",
      "message": "unreachable",
      "timestamp": 1722244377174
    }
  ],
  "logs": [
    {
      "message": [
        "panic: syscall/js: call of Value.Int on undefined"
      ],
...
      "cf": {
        "clientTcpRtt": 101,
        "longitude": "3.39030",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AF",
        "clientAcceptEncoding": "gzip, deflate, br, zstd",
        "country": "NG",
        "tlsClientAuth": {
          ...
        },
        "tlsExportedAuthenticator": {
          ...
        },
        "tlsClientHelloLength": "585",
        "colo": "LHR",
        "timezone": "Africa/Lagos",
        "verifiedBotCategory": "",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "tlsClientExtensionsSha1": "NvNr7OneGURecm6A+SxDAGU5YHs=",
        "tlsVersion": "TLSv1.3",
        "region": "Lagos",
        "regionCode": "LA",
        "city": "Lagos",
        "latitude": "6.44740",
        "tlsClientRandom": "OunCfJXpHRkwcmMKYsDVSGckSnmYkjjW7hcH3MHkCCI="
      }
```
Notice the lack of an `asn` field.

I believe the code here: https://github.com/syumai/workers/blob/6d313765fb53c065c0ca88dd6b6abedd87cd3f67/cloudflare/fetch/property.go#L187 needs to have a check around syscall/js.Value.IsUndefined().

**Comment by syumai** [comment]
This issue seems to have been fixed in #120. Thank you!
