### ISSUE TITLE
Uncaught (in promise) TypeError: Illegal invocation

### ISSUE THREAD

**Issue by cxjava** [syumai/workers#126]
When I want to run it in local for one tinygo example: https://github.com/tinygo-org/tinygo/tree/release/src/examples/wasm/callback

When I use the **worker provided** tinygo [wasm_exec.js](https://github.com/syumai/workers/blob/main/cmd/workers-assets-gen/assets/wasm_exec_tinygo.js), which will have below error. 

If I use the **offical** tinygo [wasm_exec.js](https://github.com/tinygo-org/tinygo/blob/release/targets/wasm_exec.js), which works correctly. 

@syumai  Could you help to check it? 

```
Uncaught (in promise) TypeError: Illegal invocation
    at Reflect.get (<anonymous>)
    at Object.get (wasm_exec.js:468:21)
    at Reflect.get (<anonymous>)
    at syscall/js.valueGet (wasm_exec.js:324:28)
    at main.(:8080/syscall/js.Value).Get (http://localhost:8080/wasm.wasm)
    at main.runtime.run$1$gowrapper (wasm.wasm:0x2f47)
    at main.runtime.scheduler (wasm.wasm:0x343b)
    at main._start.command_export (wasm.wasm:0x717a)
    at Object.run (wasm_exec.js:496:24)
    at wasm.js:12:10
```

I think there are some different between **worker provided** tinygo [wasm_exec.js](https://github.com/syumai/workers/blob/main/cmd/workers-assets-gen/assets/wasm_exec_tinygo.js) and **offical** tinygo [wasm_exec.js](https://github.com/tinygo-org/tinygo/blob/release/targets/wasm_exec.js)

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/14a2a114-438a-4017-a0b8-c5251c281101">

here is the code

wasm.js
```
'use strict';

const WASM_URL = 'wasm.wasm';

var wasm;

function init() {
  const go = new Go();
  if ('instantiateStreaming' in WebAssembly) {
    WebAssembly.instantiateStreaming(fetch(WASM_URL), go.importObject).then(function (obj) {
      wasm = obj.instance;
      go.run(wasm);
    })
  } else {
    fetch(WASM_URL).then(resp =>
      resp.arrayBuffer()
    ).then(bytes =>
      WebAssembly.instantiate(bytes, go.importObject).then(function (obj) {
        wasm = obj.instance;
        go.run(wasm);
      })
    )
  }
}

init();
```

index.html
```
<!DOCTYPE html>

<html>

<head>
	<meta charset="utf-8" />
	<title>Go WebAssembly</title>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<script src="wasm_exec.js" defer></script>
	<script src="wasm.js" defer></script>
</head>

<body>
	<h1>WebAssembly</h1>
	<p>Add two numbers, using WebAssembly:</p>
	<input type="number" id="a" value="0" /> + <input type="number" id="b" value="0" /> = <input type="number" id="result" readonly />
</body>

</html>
```

wasm.go
```
package main

import (
	"strconv"
	"syscall/js"
)

var a, b int

func main() {
	wait := make(chan struct{}, 0)
	document := js.Global().Get("document")
	document.Call("getElementById", "a").Set("oninput", updater(&a))
	document.Call("getElementById", "b").Set("oninput", updater(&b))
	update()
	<-wait
}

func updater(n *int) js.Func {
	return js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		*n, _ = strconv.Atoi(this.Get("value").String())
		update()
		return nil
	})
}

func update() {
	js.Global().Get("document").Call("getElementById", "result").Set("value", a+b)
}
```

main.go
```
package main

import (
	"log"
	"net/http"
	"strings"
)

const dir = "./html"

func main() {
	fs := http.FileServer(http.Dir(dir))
	log.Print("Serving " + dir + " on http://localhost:8080")
	http.ListenAndServe(":8080", http.HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
		resp.Header().Add("Cache-Control", "no-cache")
		if strings.HasSuffix(req.URL.Path, ".wasm") {
			resp.Header().Set("content-type", "application/wasm")
		}
		fs.ServeHTTP(resp, req)
	}))
}
```

build command
```
 tinygo build -o ./html/wasm.wasm -target wasm -no-debug -panic=trap -opt=z ./wasm.go
 go run main.go
```

**Comment by syumai** [comment]
@cxjava `wasm_exec.js` bundled with syumai/workers is intended for use with Cloudflare Workers, not for browsers.
It looks like you're running code in the browser, which is not a use case we support.
Please use official `wasm_exec.js` for browser usage.

**Comment by syumai** [comment]
If it's syumai/workers' side problem, please reopen this issue.
